[package]
name = "project-oculus"
version = "0.1.0"
edition = "2024"

[dependencies]
thirtyfour = "0.33"
tokio = { version = "1", features = ["rt"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
